CREATE TABLE USER (
    USER_ID VARCHAR(255) PRIMARY KEY,
    USER_PASSWORD VARCHAR(10) NOT NULL,
    USER_FNAME VARCHAR(255) NOT NULL,
    USER_LNAME VARCHAR(255) NOT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL
);